### ISSUE TITLE
Error while downloading http://10.0.41.190:8000/mono0.8.tar.bz2

### ISSUE THREAD

**Issue by langeland** [getopenmono/arduino_comp#1]
When trying to install board in the board manager I get: **Error while downloading http://10.0.41.190:8000/mono0.8.tar.bz2**

...

**Comment by stoffera** [comment]
What file are you referring to? You should use this one:
https://github.com/getopenmono/arduino_comp/releases/download/0.8/package_openmono_index.json

As explained in the getting started article:

http://developer.openmono.com/en/latest/getting-started/arduino-hackers.html

**Comment by langeland** [comment]
Ahh.. sorry, my fault... I used: https://github.com/getopenmono/arduino_comp/blob/master/package_openmono_index.json

/
